# Generated by Django 4.2.7 on 2023-11-22 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainRadar1', '0008_rename_id_unico1_programa_academicos_id_unico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha_comentario']},
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
