# Generated by Django 4.2.7 on 2023-11-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRadar1', '0009_alter_comentario_options_comentario_fecha_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa_academicos',
            name='precio_medio',
            field=models.FloatField(default=0.0),
        ),
    ]
