# Generated by Django 4.2.4 on 2023-10-21 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainRadar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='universidades',
            new_name='universidad',
        ),
    ]
