# Generated by Django 4.2.4 on 2023-10-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainRadar', '0005_remove_curso_id_programa_academico_curso_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='id_universidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainRadar.universidad'),
        ),
    ]
