# Generated by Django 4.2.4 on 2023-10-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainRadar', '0006_curso_id_universidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso_programa',
            name='id_curso',
        ),
    ]
